### ISSUE TITLE
 KeyError: '/dav/addressbooks/user/duncan@bayne.id.au/Default/' synchronising FastMail CardDAV w/ BBDB

### ISSUE THREAD

**Issue by duncan-bayne** [skarra/ASynK#69] opened 2015-06-09 12:03 UTC
I've just recursively cloned AsynK, and added a profile to synchronise my FastMail CardDAV contacts with BBDB. 

```
$ ./asynk.py --op=create-profile --name duncan --user-dir=~/.asynk.carddav --db bb cd --folder default default --store ~/.emacs.d/bbdb https://carddav.messagingengine.com/dav/addressbooks/user/duncan@bayne.id.au/Default --log=debug
Creating ASynK User directory at:  /home/duncan/.asynk.carddav
Applying base config from file /home/duncan/ASynK/config/config_v7.json...
Applying base config from file /home/duncan/ASynK/config/config_v7.json...done
Applying user customizations from file /home/duncan/.asynk.carddav/config.py...
Applying user customizations from file /home/duncan/.asynk.carddav/config.py...done
INFO:root:Creating Logs directory at: /home/duncan/.asynk.carddav/logs
[22:00:47.643     INFO] Creating Logs directory at: /home/duncan/.asynk.carddav/logs
INFO:root:Debug logging to file: /home/duncan/.asynk.carddav/logs/asynk_logs.2015-06-09.22-00-47.643341
[22:00:47.643     INFO] Debug logging to file: /home/duncan/.asynk.carddav/logs/asynk_logs.2015-06-09.22-00-47.643341
DEBUG:root:Command line: "./asynk.py --op=create-profile --name duncan --user-dir=~/.asynk.carddav --db bb cd --folder default default --store /home/duncan/.emacs.d/bbdb https://carddav.messagingengine.com/dav/addressbooks/user/duncan@bayne.id.au/Default --log=debug"
INFO:root:Deleting log files older than 7 days, if any...
[22:00:47.643     INFO] Deleting log files older than 7 days, if any...
INFO:root:Deleting log files older than 7 days, if any...done
[22:00:47.643     INFO] Deleting log files older than 7 days, if any...done
INFO:root:Successfully added profile: duncan
[22:00:47.645     INFO] Successfully added profile: duncan
```

However, when I try to synchronise I'm receiving a KeyError:

```
$ ./asynk.py --op=sync --user-dir=~/.asynk.carddav --name duncan --log=debug
Applying base config from file /home/duncan/ASynK/config/config_v7.json...
Applying base config from file /home/duncan/ASynK/config/config_v7.json...done
Applying user customizations from file /home/duncan/.asynk.carddav/config.py...
Applying user customizations from file /home/duncan/.asynk.carddav/config.py...done
INFO:root:Debug logging to file: /home/duncan/.asynk.carddav/logs/asynk_logs.2015-06-09.21-57-26.206874
[21:57:26.206     INFO] Debug logging to file: /home/duncan/.asynk.carddav/logs/asynk_logs.2015-06-09.21-57-26.206874
DEBUG:root:Command line: "./asynk.py --op=sync --user-dir=~/.asynk.carddav --name duncan --log=debug"
INFO:root:Deleting log files older than 7 days, if any...
[21:57:26.207     INFO] Deleting log files older than 7 days, if any...
INFO:root:Deleting log files older than 7 days, if any...done
[21:57:26.207     INFO] Deleting log files older than 7 days, if any...done
INFO:root:Parsing BBDB file /home/duncan/.emacs.d/bbdb...
[21:57:26.207     INFO] Parsing BBDB file /home/duncan/.emacs.d/bbdb...
DEBUG:root:New BBContactsFolder: default
[21:57:26.208    DEBUG] New BBContactsFolder: default
INFO:root:Parsing BBDB Store with encoding utf-8...
[21:57:26.208     INFO] Parsing BBDB Store with encoding utf-8...
INFO:root:Parsing BBDB Store with encoding utf-8...Success
[21:57:26.208     INFO] Parsing BBDB Store with encoding utf-8...Success
INFO:root:Successfully parsed 0 entries.
[21:57:26.208     INFO] Successfully parsed 0 entries.
Please enter username for cd2: XXXXXXXXXXXXXXXXXXXXX
Enter password for cd2: XXXXXXXXXXXXXXXXXXXXX
INFO:root:Logging into CardDAV server: https://carddav.messagingengine.com/dav/addressbooks/user/duncan@bayne.id.au/Default - user: duncan@bayne.id.au...
[21:57:33.350     INFO] Logging into CardDAV server: https://carddav.messagingengine.com/dav/addressbooks/user/duncan@bayne.id.au/Default - user: duncan@bayne.id.au...
DEBUG:root:PIMDB cd does not have email_domains.
[21:57:33.350    DEBUG] PIMDB cd does not have email_domains.
DEBUG:root:PIMDB cd does not have postal_map
[21:57:33.350    DEBUG] PIMDB cd does not have postal_map
DEBUG:root:PIMDB cd does not have notes_map
[21:57:33.350    DEBUG] PIMDB cd does not have notes_map
DEBUG:root:PIMDB cd does not have phones_map
[21:57:33.350    DEBUG] PIMDB cd does not have phones_map
DEBUG:root:Sending request OPTIONS to server carddav.messagingengine.com/dav/addressbooks/user/duncan%40bayne.id.au/Default...
[21:57:33.351    DEBUG] Sending request OPTIONS to server carddav.messagingengine.com/dav/addressbooks/user/duncan%40bayne.id.au/Default...
DEBUG:root:Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default	Method: OPTIONS
[21:57:35.234    DEBUG] Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default	Method: OPTIONS
DEBUG:root:Received Response: HTTP/1.1 401 Unauthorized

[21:57:35.543    DEBUG] Received Response: HTTP/1.1 401 Unauthorized

DEBUG:root:Sending request OPTIONS to server carddav.messagingengine.com/dav/addressbooks/user/duncan%40bayne.id.au/Default...
[21:57:35.543    DEBUG] Sending request OPTIONS to server carddav.messagingengine.com/dav/addressbooks/user/duncan%40bayne.id.au/Default...
DEBUG:root:Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default	Method: OPTIONS
[21:57:35.544    DEBUG] Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default	Method: OPTIONS
DEBUG:root:Received Response: HTTP/1.1 200 OK

[21:57:35.850    DEBUG] Received Response: HTTP/1.1 200 OK

DEBUG:root:Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default	Method: PROPFIND
[21:57:35.851    DEBUG] Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default	Method: PROPFIND
DEBUG:root:Received Response: HTTP/1.1 207 Multi-Status

[21:57:36.567    DEBUG] Received Response: HTTP/1.1 207 Multi-Status

Found current principal path: /dav/principals/user/duncan%40bayne.id.au/
DEBUG:root:Sending Request URL: /dav/principals/user/duncan%40bayne.id.au/	Method: PROPFIND
[21:57:37.589    DEBUG] Sending Request URL: /dav/principals/user/duncan%40bayne.id.au/	Method: PROPFIND
DEBUG:root:Received Response: HTTP/1.1 207 Multi-Status

[21:57:38.308    DEBUG] Received Response: HTTP/1.1 207 Multi-Status

DEBUG:root:Found principal: duncan@bayne.id.au
[21:57:38.310    DEBUG] Found principal: duncan@bayne.id.au
DEBUG:root:CDPIMDB.fetch_folders(): Begin
[21:57:38.311    DEBUG] CDPIMDB.fetch_folders(): Begin
DEBUG:root:Exploring following root paths: ['/dav/addressbooks/user/duncan@bayne.id.au/']
[21:57:38.311    DEBUG] Exploring following root paths: ['/dav/addressbooks/user/duncan@bayne.id.au/']
DEBUG:root:Processing root path /dav/addressbooks/user/duncan@bayne.id.au/
[21:57:38.311    DEBUG] Processing root path /dav/addressbooks/user/duncan@bayne.id.au/
DEBUG:root:Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/	Method: PROPFIND
[21:57:39.227    DEBUG] Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/	Method: PROPFIND
DEBUG:root:Received Response: HTTP/1.1 207 Multi-Status

[21:57:39.946    DEBUG] Received Response: HTTP/1.1 207 Multi-Status

DEBUG:root:  Found following properties: ['/dav/addressbooks/user/duncan%40bayne.id.au/', '/dav/addressbooks/user/duncan%40bayne.id.au/Default/', '/dav/addressbooks/user/masteruser%40bayne.id.au/Shared/'].
[21:57:39.947    DEBUG]   Found following properties: ['/dav/addressbooks/user/duncan%40bayne.id.au/', '/dav/addressbooks/user/duncan%40bayne.id.au/Default/', '/dav/addressbooks/user/masteruser%40bayne.id.au/Shared/'].
Traceback (most recent call last):
  File "./asynk.py", line 302, in <module>
    main()
  File "./asynk.py", line 299, in main
    asynk.dispatch()
  File "/home/duncan/ASynK/asynk/asynk_core.py", line 97, in dispatch
    res = getattr(self, self.get_op())()
  File "/home/duncan/ASynK/asynk/asynk_core.py", line 366, in op_sync
    pname = self._load_profile()
  File "/home/duncan/ASynK/asynk/asynk_core.py", line 584, in _load_profile
    self._login()
  File "/home/duncan/ASynK/asynk/asynk_core.py", line 85, in _login
    coll.login()
  File "/home/duncan/ASynK/asynk/state_collection.py", line 295, in login
    self.get_username(), self.get_pwd())
  File "/home/duncan/ASynK/asynk/pimdb_cd.py", line 56, in __init__
    self.set_folders()
  File "/home/duncan/ASynK/asynk/pimdb_cd.py", line 110, in set_folders
    fs = self.fetch_folders()
  File "/home/duncan/ASynK/asynk/pimdb_cd.py", line 337, in fetch_folders
    props = results[rurl]
KeyError: '/dav/addressbooks/user/duncan@bayne.id.au/Default/'
```

**Comment by skarra** [comment] 2015-06-14 04:26
Hm, interesting. The problem is your username is a full email address, and there is some urlencode / urldecode mismatch going on. I need to verify what is the standards compiant behaviour here and will fix it accordingly.

I have just created a trial account on Fastmail and will explore this further.

**Comment by duncan-bayne** [comment] 2015-06-14 04:46
@skarra Fastmail support is excellent if you have any questions; also, I have a paid account and I'm happy to ask any questions myself.  Just let me know.

**Comment by duncan-bayne** [comment] 2015-06-14 04:46
In fact, I'll let them know about this issue, as they may wish to comment on it.

**Comment by skarra** [comment] 2015-06-14 06:00
Sure. At this time I am unsure if this is a bug in Fastmail's carddav implementation or in ASynK. Will update as I get more clarity.

**Comment by duncan-bayne** [comment] 2015-06-14 10:24
Thanks - yeah, I didn't know either which is why I opened this issue :)  Let me know if there's anything I can do to help with debugging.  I'm a Lisp newbie but can follow instructions :)

**Comment by skarra** [comment] 2015-06-14 10:35
I think the handling cold be improved in ASynK, and have pushed a fix to the ```cd-names``` branch. Can you take a look?

But be warned that you may run into other issues. For e.g. I am not getting updates from Fastmail (i.e. updating a contact in Fastmail does not seem to set the updated timestamp on the contact, leading to problems in synching them back into BBDB. But feel free to open other issues as you find them.

You can close this issue if you are able to get past the first hurdle you reported.

**Comment by duncan-bayne** [comment] 2015-06-14 12:56
Still failing I'm afraid, but differently this time:

```
➜  ASynK git:(cd-names) ./asynk.py --op=create-profile --name duncan --user-dir=~/.asynk.carddav --db bb cd --folder default default --store ~/.emacs.d/bbdb https://carddav.messagingengine.com/dav/addressbooks/u
ser/duncan@bayne.id.au/Default --log=debug
Creating ASynK User directory at:  /home/duncan/.asynk.carddav
Applying base config from file /home/duncan/emacs-setup/emacs.d/ASynK/config/config_v7.json...
Applying base config from file /home/duncan/emacs-setup/emacs.d/ASynK/config/config_v7.json...done
Applying user customizations from file /home/duncan/.asynk.carddav/config.py...
Applying user customizations from file /home/duncan/.asynk.carddav/config.py...done
INFO:root:Creating Logs directory at: /home/duncan/.asynk.carddav/logs
[22:53:05.312     INFO] Creating Logs directory at: /home/duncan/.asynk.carddav/logs
INFO:root:Debug logging to file: /home/duncan/.asynk.carddav/logs/asynk_logs.2015-06-14.22-53-05.312804
[22:53:05.312     INFO] Debug logging to file: /home/duncan/.asynk.carddav/logs/asynk_logs.2015-06-14.22-53-05.312804
DEBUG:root:Command line: "./asynk.py --op=create-profile --name duncan --user-dir=~/.asynk.carddav --db bb cd --folder default default --store /home/duncan/.emacs.d/bbdb https://carddav.messagingengine.com/dav/a
ddressbooks/user/duncan@bayne.id.au/Default --log=debug"
INFO:root:Deleting log files older than 7 days, if any...
[22:53:05.313     INFO] Deleting log files older than 7 days, if any...
INFO:root:Deleting log files older than 7 days, if any...done
[22:53:05.313     INFO] Deleting log files older than 7 days, if any...done
INFO:root:Successfully added profile: duncan
[22:53:05.315     INFO] Successfully added profile: duncan
➜  ASynK git:(cd-names)  ./asynk.py --op=sync --user-dir=~/.asynk.carddav --name duncan --log=debug
Applying base config from file /home/duncan/emacs-setup/emacs.d/ASynK/config/config_v7.json...
Applying base config from file /home/duncan/emacs-setup/emacs.d/ASynK/config/config_v7.json...done
Applying user customizations from file /home/duncan/.asynk.carddav/config.py...
Applying user customizations from file /home/duncan/.asynk.carddav/config.py...done
INFO:root:Debug logging to file: /home/duncan/.asynk.carddav/logs/asynk_logs.2015-06-14.22-53-16.249760
[22:53:16.249     INFO] Debug logging to file: /home/duncan/.asynk.carddav/logs/asynk_logs.2015-06-14.22-53-16.249760
DEBUG:root:Command line: "./asynk.py --op=sync --user-dir=~/.asynk.carddav --name duncan --log=debug"
INFO:root:Deleting log files older than 7 days, if any...
[22:53:16.250     INFO] Deleting log files older than 7 days, if any...
INFO:root:Deleting log files older than 7 days, if any...done
[22:53:16.250     INFO] Deleting log files older than 7 days, if any...done
INFO:root:Parsing BBDB file /home/duncan/.emacs.d/bbdb...
[22:53:16.250     INFO] Parsing BBDB file /home/duncan/.emacs.d/bbdb...
DEBUG:root:New BBContactsFolder: default
[22:53:16.250    DEBUG] New BBContactsFolder: default
INFO:root:Parsing BBDB Store with encoding utf-8...
[22:53:16.250     INFO] Parsing BBDB Store with encoding utf-8...
INFO:root:Parsing BBDB Store with encoding utf-8...Success
[22:53:16.251     INFO] Parsing BBDB Store with encoding utf-8...Success
INFO:root:Successfully parsed 0 entries.
[22:53:16.251     INFO] Successfully parsed 0 entries.
Please enter username for cd2: duncan@bayne.id.au
Enter password for cd2: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
INFO:root:Logging into CardDAV server: https://carddav.messagingengine.com/dav/addressbooks/user/duncan@bayne.id.au/Default - user: duncan@bayne.id.au...
[22:53:39.573     INFO] Logging into CardDAV server: https://carddav.messagingengine.com/dav/addressbooks/user/duncan@bayne.id.au/Default - user: duncan@bayne.id.au...
DEBUG:root:PIMDB cd does not have email_domains.
[22:53:39.573    DEBUG] PIMDB cd does not have email_domains.
DEBUG:root:PIMDB cd does not have postal_map
[22:53:39.573    DEBUG] PIMDB cd does not have postal_map
DEBUG:root:PIMDB cd does not have notes_map
[22:53:39.574    DEBUG] PIMDB cd does not have notes_map
DEBUG:root:PIMDB cd does not have phones_map
[22:53:39.574    DEBUG] PIMDB cd does not have phones_map
DEBUG:root:Sending request OPTIONS to server carddav.messagingengine.com/dav/addressbooks/user/duncan%40bayne.id.au/Default...
[22:53:39.574    DEBUG] Sending request OPTIONS to server carddav.messagingengine.com/dav/addressbooks/user/duncan%40bayne.id.au/Default...
DEBUG:root:Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default     Method: OPTIONS
[22:53:41.353    DEBUG] Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default        Method: OPTIONS
DEBUG:root:Received Response: HTTP/1.1 401 Unauthorized

[22:53:41.609    DEBUG] Received Response: HTTP/1.1 401 Unauthorized

DEBUG:root:Sending request OPTIONS to server carddav.messagingengine.com/dav/addressbooks/user/duncan%40bayne.id.au/Default...
[22:53:41.610    DEBUG] Sending request OPTIONS to server carddav.messagingengine.com/dav/addressbooks/user/duncan%40bayne.id.au/Default...
DEBUG:root:Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default     Method: OPTIONS
[22:53:41.610    DEBUG] Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default        Method: OPTIONS
DEBUG:root:Received Response: HTTP/1.1 200 OK

[22:53:41.968    DEBUG] Received Response: HTTP/1.1 200 OK

DEBUG:root:Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default     Method: PROPFIND
[22:53:41.968    DEBUG] Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default        Method: PROPFIND
DEBUG:root:Received Response: HTTP/1.1 207 Multi-Status

[22:53:42.582    DEBUG] Received Response: HTTP/1.1 207 Multi-Status

Found current principal path: /dav/principals/user/duncan%40bayne.id.au/
DEBUG:root:Sending Request URL: /dav/principals/user/duncan%40bayne.id.au/      Method: PROPFIND
[22:53:43.605    DEBUG] Sending Request URL: /dav/principals/user/duncan%40bayne.id.au/ Method: PROPFIND
DEBUG:root:Received Response: HTTP/1.1 207 Multi-Status

[22:53:44.221    DEBUG] Received Response: HTTP/1.1 207 Multi-Status

DEBUG:root:Found principal: duncan@bayne.id.au
[22:53:44.224    DEBUG] Found principal: duncan@bayne.id.au
DEBUG:root:CDPIMDB.fetch_folders(): Begin
[22:53:44.224    DEBUG] CDPIMDB.fetch_folders(): Begin
DEBUG:root:Exploring following root paths: ['/dav/addressbooks/user/duncan@bayne.id.au/']
[22:53:44.224    DEBUG] Exploring following root paths: ['/dav/addressbooks/user/duncan@bayne.id.au/']
DEBUG:root:Processing root path /dav/addressbooks/user/duncan@bayne.id.au/
[22:53:44.225    DEBUG] Processing root path /dav/addressbooks/user/duncan@bayne.id.au/
DEBUG:root:Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/    Method: PROPFIND
[22:53:45.244    DEBUG] Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/       Method: PROPFIND
DEBUG:root:Received Response: HTTP/1.1 207 Multi-Status

[22:53:45.858    DEBUG] Received Response: HTTP/1.1 207 Multi-Status

DEBUG:root:  Found following properties: ['/dav/addressbooks/user/duncan%40bayne.id.au/', '/dav/addressbooks/user/duncan%40bayne.id.au/Default/', '/dav/addressbooks/user/masteruser%40bayne.id.au/Shared/'].
[22:53:45.859    DEBUG]   Found following properties: ['/dav/addressbooks/user/duncan%40bayne.id.au/', '/dav/addressbooks/user/duncan%40bayne.id.au/Default/', '/dav/addressbooks/user/masteruser%40bayne.id.au/Sha
red/'].
DEBUG:root:    Resource type of prop: <Element '{DAV:}resourcetype' at 0x7ffff42720d0>.
[22:53:45.860    DEBUG]     Resource type of prop: <Element '{DAV:}resourcetype' at 0x7ffff42720d0>.
DEBUG:root:Found Folder Default         in URI "/dav/addressbooks/user/duncan@bayne.id.au/Default/"
[22:53:45.860    DEBUG] Found Folder Default         in URI "/dav/addressbooks/user/duncan@bayne.id.au/Default/"
DEBUG:root:    Resource type of prop: <Element '{DAV:}resourcetype' at 0x7ffff4272310>.
[22:53:45.860    DEBUG]     Resource type of prop: <Element '{DAV:}resourcetype' at 0x7ffff4272310>.
DEBUG:root:Found Folder .au/Shared      in URI "/dav/addressbooks/user/masteruser@bayne.id.au/Shared/"
[22:53:45.860    DEBUG] Found Folder .au/Shared      in URI "/dav/addressbooks/user/masteruser@bayne.id.au/Shared/"
DEBUG:root:CDPIMDB.fetch_folders(): Done.
[22:53:45.860    DEBUG] CDPIMDB.fetch_folders(): Done.
DEBUG:root:Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/    Method: PROPFIND
[22:53:46.882    DEBUG] Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/       Method: PROPFIND
DEBUG:root:Received Response: HTTP/1.1 207 Multi-Status

[22:53:47.497    DEBUG] Received Response: HTTP/1.1 207 Multi-Status

DEBUG:root:Coud not find default adbk Property. Trying to use first of the available contacts folders
[22:53:47.497    DEBUG] Coud not find default adbk Property. Trying to use first of the available contacts folders
INFO:root:Logging into CardDAV server: https://carddav.messagingengine.com/dav/addressbooks/user/duncan@bayne.id.au/Default - user: duncan@bayne.id.au... done.
[22:53:47.498     INFO] Logging into CardDAV server: https://carddav.messagingengine.com/dav/addressbooks/user/duncan@bayne.id.au/Default - user: duncan@bayne.id.au... done.
DEBUG:root:pimdbs : [<pimdb_bb.BBPIMDB object at 0x7ffff4c2f190>, <pimdb_cd.CDPIMDB object at 0x7ffff4c2fd10>]
[22:53:47.498    DEBUG] pimdbs : [<pimdb_bb.BBPIMDB object at 0x7ffff4c2f190>, <pimdb_cd.CDPIMDB object at 0x7ffff4c2fd10>]
DEBUG:root:pname : duncan
[22:53:47.498    DEBUG] pname : duncan
DEBUG:root:fid1  : default
[22:53:47.498    DEBUG] fid1  : default
DEBUG:root:fid2  : default/
[22:53:47.498    DEBUG] fid2  : default/
DEBUG:root:db1id : bb
[22:53:47.498    DEBUG] db1id : bb
DEBUG:root:db    : <pimdb_bb.BBPIMDB object at 0x7ffff4c2f190>
[22:53:47.498    DEBUG] db    : <pimdb_bb.BBPIMDB object at 0x7ffff4c2f190>
DEBUG:root:Updated fid1  : default
[22:53:47.498    DEBUG] Updated fid1  : default
ERROR:root:Could not find folder with ID fid2: default/
[22:53:47.498    ERROR] Could not find folder with ID fid2: default/
Traceback (most recent call last):
  File "./asynk.py", line 302, in <module>
    main()
  File "./asynk.py", line 299, in main
    asynk.dispatch()
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/asynk_core.py", line 97, in dispatch
    res = getattr(self, self.get_op())()
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/asynk_core.py", line 385, in op_sync
    dr=self.is_dry_run())
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/sync.py", line 96, in __init__
    raise Exception()
Exception
```

**Comment by skarra** [comment] 2015-06-14 13:05
Can you edit your state.json file and remove the trailing slash after 'default' for foid?

**Comment by duncan-bayne** [comment] 2015-06-15 11:01
Okay, closer this time :smile: Synchronisation started and ran, but fell over part of the way through, with this error:

```
DEBUG:root:Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default/99ce5b3128.vcf      Method: PUT
[20:49:19.253    DEBUG] Sending Request URL: /dav/addressbooks/user/duncan%40bayne.id.au/Default/99ce5b3128.vcf Method: PUT
DEBUG:root:Received Response: HTTP/1.1 204 No Content

[20:49:19.869    DEBUG] Received Response: HTTP/1.1 204 No Content

CRITICAL:root:Exception ('VCARD components must contain at least 1 FN') while syncing profile duncan
[20:49:19.870 CRITICAL] Exception ('VCARD components must contain at least 1 FN') while syncing profile duncan
CRITICAL:root:Traceback (most recent call last):
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/asynk_core.py", line 396, in op_sync
    result = sync.sync(self.get_sync_dir())
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/sync.py", line 300, in sync
    ret2 = sl2.sync_to_folder(self.get_f1())
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/sync.py", line 498, in sync_to_folder
    res1 = self.send_news_to_folder(df)
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/sync.py", line 446, in send_news_to_folder
    res = res and self.fold.writeback_sync_tags(self.get_pname(), items)
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/folder_cd.py", line 270, in writeback_sync_tags
    success = success and item.save()
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/contact_cd.py", line 126, in save
    vcf_data = vco.serialize()
  File "/home/duncan/emacs-setup/emacs.d/ASynK/lib/vobject/vobject/base.py", line 186, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/home/duncan/emacs-setup/emacs.d/ASynK/lib/vobject/vobject/behavior.py", line 148, in serialize
    if validate: cls.validate(obj, raiseException=True)
  File "/home/duncan/emacs-setup/emacs.d/ASynK/lib/vobject/vobject/behavior.py", line 91, in validate
    raise base.ValidateError(m % (cls.name, val[0], key))
ValidateError: 'VCARD components must contain at least 1 FN'

[20:49:19.873 CRITICAL] Traceback (most recent call last):
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/asynk_core.py", line 396, in op_sync
    result = sync.sync(self.get_sync_dir())
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/sync.py", line 300, in sync
    ret2 = sl2.sync_to_folder(self.get_f1())
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/sync.py", line 498, in sync_to_folder
    res1 = self.send_news_to_folder(df)
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/sync.py", line 446, in send_news_to_folder
    res = res and self.fold.writeback_sync_tags(self.get_pname(), items)
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/folder_cd.py", line 270, in writeback_sync_tags
    success = success and item.save()
  File "/home/duncan/emacs-setup/emacs.d/ASynK/asynk/contact_cd.py", line 126, in save
    vcf_data = vco.serialize()
  File "/home/duncan/emacs-setup/emacs.d/ASynK/lib/vobject/vobject/base.py", line 186, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/home/duncan/emacs-setup/emacs.d/ASynK/lib/vobject/vobject/behavior.py", line 148, in serialize
    if validate: cls.validate(obj, raiseException=True)
  File "/home/duncan/emacs-setup/emacs.d/ASynK/lib/vobject/vobject/behavior.py", line 91, in validate
    raise base.ValidateError(m % (cls.name, val[0], key))
ValidateError: 'VCARD components must contain at least 1 FN'
```

I'm not sure which contact is doing this; the last VCF in the log (`99ce5b3128`) looks sane to me.

**Comment by skarra** [comment] 2015-06-15 11:05
Can you update to latest on cd-names? I pushed a fix to just this problem via https://github.com/skarra/ASynK/issues/70

**Comment by duncan-bayne** [comment] 2015-06-15 11:09
Hah, sorry, missed that - I'd assumed it was something wrong with my vcards.  I'll try again ...

**Comment by duncan-bayne** [comment] 2015-06-15 11:25
Worked a treat, thanks :smile: :+1:

**Comment by skarra** [comment] 2015-06-15 11:26
Aweswome. Closing this now.

**Closed by skarra** 2015-06-15 11:26 UTC
Labels: Bug, CardDAV
